import PdfPrinter from "pdfmake";
import type { Content, TDocumentDefinitions } from "pdfmake/interfaces";
import type { ConservationReport } from "@wr/shared";
import { AppError } from "../../../core/errors.js";
import type { ReportExporter, StoredRun } from "../types.js";
import {
  conflictChartSvg,
  spatialMapSvg,
  trendChartSvg,
} from "./svg-charts.js";

const MAX_PDF_PAGES = 12;
const fonts = {
  Helvetica: {
    normal: "Helvetica",
    bold: "Helvetica-Bold",
    italics: "Helvetica-Oblique",
    bolditalics: "Helvetica-BoldOblique",
  },
};
const printer = new PdfPrinter(fonts);

function dateInColombo(value: string, includeTime = false): string {
  return new Intl.DateTimeFormat("en-GB", {
    timeZone: "Asia/Colombo",
    year: "numeric",
    month: "short",
    day: "2-digit",
    ...(includeTime
      ? { hour: "2-digit", minute: "2-digit", hourCycle: "h23" as const }
      : {}),
  }).format(new Date(value));
}

function filterSummary(report: ConservationReport): string {
  const parts = [
    `Category group: ${report.filters.categoryGroup}`,
    `Types: ${report.filters.types.length ? report.filters.types.join(", ") : "All"}`,
    `Sources: ${report.filters.sources.length ? report.filters.sources.join(", ") : "All"}`,
    `Rejected incidents: ${report.filters.includeRejected ? "included" : "excluded"}`,
  ];
  if (report.filters.sectorId)
    parts.push(`Sector ID: ${report.filters.sectorId}`);
  return parts.join(" · ");
}

function table(
  headers: string[],
  rows: (string | number)[][],
  widths: (number | "*")[] = headers.map(() => "*"),
): Content {
  return {
    table: {
      headerRows: 1,
      widths,
      body: [
        headers.map((text) => ({
          text,
          bold: true,
          color: "#14352b",
          fillColor: "#edf2ec",
        })),
        ...rows.map((row) => row.map((text) => String(text))),
      ],
    },
    layout: {
      hLineColor: "#dce5dc",
      vLineColor: "#dce5dc",
      paddingLeft: () => 6,
      paddingRight: () => 6,
      paddingTop: () => 4,
      paddingBottom: () => 4,
    },
    fontSize: 9,
    margin: [0, 6, 0, 8],
  };
}

function reportDefinition(
  run: StoredRun & { report: ConservationReport },
): TDocumentDefinitions {
  const report = run.report;
  const snapshotHash = run.snapshotSha256;
  if (!snapshotHash)
    throw new AppError(
      "This report is missing its integrity hash.",
      409,
      "REPORT_NOT_EXPORTABLE",
    );
  const trendRows = report.trend.map((point) => [
    point.label,
    point.count.toLocaleString("en-US"),
  ]);
  const breakdown = report.breakdown
    .slice(0, 20)
    .map((row) => [
      row.type,
      row.sectorName,
      row.count.toLocaleString("en-US"),
      `${row.sharePercent.toFixed(1)}%`,
    ]);
  if (report.breakdown.length > 20)
    breakdown.push([
      "",
      `+ ${report.breakdown.length - 20} more rows in the CSV export`,
      "",
      "",
    ]);

  const hotspotRows = report.hotspots.cells
    .filter((cell) => cell.isHotspot)
    .slice(0, 10)
    .map((cell) => [
      cell.sectorName ?? "Unassigned",
      cell.count.toLocaleString("en-US"),
      `${cell.riskClass} of 5`,
    ]);
  const priorityRows = report.priorityCells.map((cell, index) => [
    String(index + 1),
    cell.sectorName ?? "Unassigned",
    `${cell.centre.latitude.toFixed(3)}, ${cell.centre.longitude.toFixed(3)}`,
    cell.incidents.toLocaleString("en-US"),
    cell.daysSincePatrol === null ? "Never" : String(cell.daysSincePatrol),
  ]);
  const stretchRows = report.conflicts.byStretch.map((stretch) => [
    stretch.stretchName,
    stretch.communityReports.toLocaleString("en-US"),
    stretch.collarBreaches.toLocaleString("en-US"),
  ]);

  const content: Content[] = [
    {
      text: "Department of Wildlife Conservation — Sri Lanka (prototype)",
      style: "department",
    },
    { text: "Conservation Outcome Report", style: "title" },
    { text: report.park.name, style: "park" },
    {
      text: `Period: ${dateInColombo(report.filters.from)} – ${dateInColombo(report.filters.to)} (Colombo time)`,
    },
    { text: `Report code: ${run.code}`, style: "mono" },
    {
      text: `Generated by: ${run.requesterName} (${run.requesterRole})`,
      margin: [0, 4, 0, 0],
    },
    {
      text: `Generated: ${dateInColombo(report.generatedAt, true)} Colombo time`,
    },
    { text: `Filters: ${filterSummary(report)}`, margin: [0, 6, 0, 2] },
    {
      text: "Key indicators",
      style: "section",
      margin: [0, 12, 0, 2],
    },
    table(
      ["Indicator", "Value"],
      [
        ["Total incidents", report.kpis.totalIncidents],
        ["Previous-period incidents", report.kpis.previousPeriodIncidents],
        [
          "Change",
          report.kpis.changePercent === null
            ? report.kpis.changeKind
            : `${report.kpis.changePercent.toFixed(1)}% (${report.kpis.changeKind})`,
        ],
        ["Hotspot cells", report.kpis.hotspotCells],
        [
          "Patrol gap area",
          report.kpis.patrolGapAreaKm2 === null
            ? "Not configured"
            : `${report.kpis.patrolGapAreaKm2.toFixed(2)} km²`,
        ],
        ["Community conflict reports", report.kpis.communityConflictReports],
        ["Collar breaches", report.kpis.collarBreaches],
      ],
    ),
    { text: "Summary", style: "section" },
    ...report.summarySentences.map((text): Content => ({
      text: `• ${text}`,
      margin: [0, 2, 0, 2],
    })),
    { text: "Incident trend", style: "section", pageBreak: "before" },
    ...(report.trend.length
      ? [{ svg: trendChartSvg(report.trend), width: 500 }]
      : [{ text: "No incidents were recorded in this period." }]),
    table(["Period", "Incidents"], trendRows),
    { text: "Sector breakdown (top 20)", style: "section" },
    table(["Type", "Sector", "Incidents", "Share"], breakdown, [
      170,
      "*",
      65,
      65,
    ]),
    { text: "Data quality", style: "section" },
    table(
      ["Measure", "Count"],
      Object.entries(report.dataQuality).map(([key, value]) => [
        key,
        value.toLocaleString("en-US"),
      ]),
    ),
    { text: "Spatial analysis", style: "section", pageBreak: "before" },
    { svg: spatialMapSvg(report), width: 500 },
    {
      text: `Grid size: ${report.hotspots.cellSizeMeters} m · Risk classes: 1–5 · Priority-cell centres are rounded to 3 decimals.`,
      style: "small",
    },
    { text: "Hotspot cells", style: "section" },
    table(["Sector", "Incidents", "Risk class"], hotspotRows),
    { text: "Priority cells (cell centre)", style: "section" },
    table(
      ["Rank", "Sector", "Lat, lon", "Incidents", "Days since patrol"],
      priorityRows,
    ),
    { text: "Conflict trends", style: "section", pageBreak: "before" },
    ...(report.conflicts.series.length
      ? [{ svg: conflictChartSvg(report.conflicts.series), width: 500 }]
      : [{ text: "No conflict activity was recorded in this period." }]),
    table(
      ["Boundary stretch", "Community reports", "Collar breaches"],
      stretchRows.length
        ? stretchRows
        : [["No defined boundary stretch", "0", "0"]],
    ),
    {
      text: "Sources are counted separately and are not deduplicated. One event can appear in more than one series.",
      style: "small",
      margin: [0, 4, 0, 0],
    },
  ];

  return {
    pageSize: "A4",
    pageMargins: [42, 54, 42, 50],
    defaultStyle: { font: "Helvetica", fontSize: 10, color: "#1f2937" },
    styles: {
      department: { fontSize: 9, color: "#166534", bold: true },
      title: { fontSize: 22, bold: true, margin: [0, 7, 0, 2] },
      park: { fontSize: 16, bold: true, margin: [0, 0, 0, 8] },
      section: {
        fontSize: 13,
        bold: true,
        color: "#14352b",
        margin: [0, 10, 0, 4],
      },
      mono: { fontSize: 9, color: "#475569" },
      small: { fontSize: 8, color: "#64748b" },
    },
    header: () => ({
      text: `${report.park.name}  ·  ${run.code}`,
      alignment: "right",
      fontSize: 8,
      color: "#64748b",
      margin: [42, 22, 42, 0],
    }),
    footer: (currentPage: number, pageCount: number) => ({
      stack: [
        {
          columns: [
            {
              text: `Snapshot SHA-256: ${snapshotHash}${report.syntheticDemo === true ? "  ·  Synthetic demo data" : ""}`,
              fontSize: 7,
              color: "#64748b",
            },
            {
              width: 70,
              text: `Page ${currentPage} of ${pageCount}`,
              alignment: "right",
              fontSize: 7,
              color: "#64748b",
            },
          ],
        },
        {
          text: "Generated by Wana Rakshaka prototype — not an official government document.",
          alignment: "center",
          fontSize: 7,
          color: "#64748b",
        },
      ],
      margin: [42, 0, 42, 18],
    }),
    info: {
      title: "Conservation Outcome Report",
      author: "Department of Wildlife Conservation — Sri Lanka (prototype)",
      subject: `${report.park.name} ${report.filters.from} to ${report.filters.to}`,
      creator: "Wana Rakshaka prototype",
      producer: "pdfmake",
      creationDate: new Date(report.generatedAt),
      modDate: new Date(report.generatedAt),
    },
    content,
  };
}

function renderPdf(definition: TDocumentDefinitions): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    const document = printer.createPdfKitDocument(definition);
    document.on("data", (chunk: Buffer | Uint8Array) =>
      chunks.push(Buffer.from(chunk)),
    );
    document.on("error", reject);
    document.on("end", () => resolve(Buffer.concat(chunks)));
    document.end();
  });
}

export const pdfExporter: ReportExporter = {
  format: "PDF",
  mimeType: "application/pdf",
  extension: "pdf",
  async render(run: StoredRun & { report: ConservationReport }) {
    const bytes = await renderPdf(reportDefinition(run));
    const pageCount =
      Buffer.from(bytes)
        .toString("latin1")
        .match(/\/Type\s*\/Page\b/g)?.length ?? 0;
    if (pageCount > MAX_PDF_PAGES)
      throw new AppError(
        "This report is too large to export as PDF.",
        413,
        "EXPORT_TOO_LARGE",
      );
    return bytes;
  },
};
